[package]
name = "frances-workflow"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
deno_ast.workspace = true
parking_lot.workspace = true
rquickjs.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
shell-words.workspace = true
thiserror.workspace = true
twox-hash.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync"] }
