[package]
name = "frances-worker"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "frances-worker"
path = "src/main.rs"

[dependencies]
frances-core.workspace = true
frances-shell.workspace = true
frances-worker-protocol.workspace = true
globset.workspace = true
grep-matcher.workspace = true
grep-regex.workspace = true
grep-searcher.workspace = true
ignore.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
