
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async frontendReady() : Promise<Result<AppInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("frontend_ready") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendPrompt(text: string) : Promise<void> {
    await TAURI_INVOKE("send_prompt", { text });
},
async interrupt() : Promise<void> {
    await TAURI_INVOKE("interrupt");
},
/**
 * Ctrl+Shift+I in the frontend. Backed by tauri's `devtools` feature.
 */
async toggleDevtools() : Promise<void> {
    await TAURI_INVOKE("toggle_devtools");
},
async respondPermission(decision: string, details: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("respond_permission", { decision, details }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Show a save dialog and write the current workspace as a workspace
 * file. Returns the saved path, or `None` if the user cancelled.
 */
async saveWorkspace() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_workspace") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Attach the frontend to an entity's stream. `catch_up` replays every
 * persisted item before tailing (a tab opening); without it the
 * stream just starts tailing (an inline live view).
 */
async subscribeEntity(entityId: string, catchUp: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_entity", { entityId, catchUp }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unsubscribeEntity(entityId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unsubscribe_entity", { entityId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Point-read one settle artifact (e.g. a shell's `llm_digest`).
 */
async readEntityArtifact(entityId: string, tag: string) : Promise<Result<JsonValue | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_entity_artifact", { entityId, tag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
uiEvent: UiEvent
}>({
uiEvent: "ui-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AppInfo = { sessionId: string }
/**
 * One entry in a structured diff. `Context` carries the post-side line
 * number (1-based); `Added` / `Removed` carry only the raw line content.
 */
export type DiffOp = { Context: { text: string; line: number } } | { Added: string } | { Removed: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Whether an entity's producer is still running. The only envelope
 * field besides identity: core machinery (forced settle, subscription
 * gating) reads it, so it lives outside the opaque snapshot payload.
 */
export type Lifecycle = "live" | "settled"
/**
 * Terminal status for [`SectionKind::Reasoning`].
 */
export type ReasoningState = "Streaming" | "Done"
/**
 * Section identity, scoped to one workflow invocation. Monotonically
 * assigned by `transcript.push` on the workflow side. The frontend
 * uses it to route subsequent events to the right rendered section.
 */
export type SectionId = number
/**
 * What kind of section, and any bounded metadata that rides with it.
 * One variant per section presentation in the UI. The frontend
 * matches on this to pick a rendering when a new section id is seen.
 */
export type SectionKind = 
/**
 * `MarkdownSection` — streaming text. `source` names the speaker;
 * the frontend renders markdown for `source != User` and plain
 * text for User source.
 */
{ type: "markdown"; source: Source } | 
/**
 * `ErrorSection` — one-shot error message.
 */
{ type: "error" } | 
/**
 * `ToolUseSection` — one-shot "→ tool_name" marker. `detail` is
 * the optional human-readable suffix produced by the tool's
 * `describe(call)` method.
 */
{ type: "tool_use"; name: string; detail: string | null } | 
/**
 * `JsonSection` — single tagged JSON value. Immutable after push.
 */
{ type: "json"; tag: string; value: JsonValue } | 
/**
 * `ReasoningSection` — streaming model reasoning. `state`
 * transitions `Streaming → Done` on close.
 */
{ type: "reasoning"; state: ReasoningState } | 
/**
 * `DiffSection` — one-shot structured diff produced by a file-
 * edit tool.
 */
{ type: "diff"; lines: DiffOp[] } | 
/**
 * `EntityRefSection` — one-shot pointer at an entity. The
 * transcript carries only the reference; the entity's snapshot
 * (and, on demand, its stream) render it. Dumb by design: the
 * entity exists independently via the registry/hub, refs are
 * optional decoration.
 */
{ type: "entity_ref"; entity_id: string }
/**
 * Snapshot payload of the singleton session entity.
 */
export type SessionSnapshot = { title: string | null; usage: Usage | null; 
/**
 * Footer busy-indicator text (the workflow's `setStatus`). Not
 * meaningful after settle; a fresh session starts with `None`.
 */
busy: string | null }
/**
 * Who produced a [`SectionKind::Markdown`] section. The frontend
 * styles each speaker differently and gates markdown rendering
 * (`source != User`).
 */
export type Source = "user" | "assistant" | "internal"
export type UiEvent = { type: "reset" } | { type: "replay_end" } | { type: "section_append"; id: SectionId; kind: SectionKind; delta: string } | { type: "section_close"; id: SectionId; truncated: boolean } | 
/**
 * Latest-wins entity state. `snapshot` is opaque at this boundary;
 * the frontend picks a renderer by `kind` and interprets it there.
 */
{ type: "entity_upsert"; entity_id: string; kind: string; lifecycle: Lifecycle; snapshot: JsonValue } | 
/**
 * One item of a subscribed entity's stream; `seq` dedupes across
 * the catch-up/live splice.
 */
{ type: "entity_stream"; entity_id: string; seq: number; payload: JsonValue } | { type: "error"; message: string } | { type: "permission"; prompt: string }
/**
 * Token-usage report. Universal shape; `cached_input_tokens` mirrors
 * OpenAI's `prompt_tokens_details.cached_tokens` for the wires that
 * surface it.
 */
export type Usage = { prompt_tokens: number; completion_tokens: number; total_tokens: number; cached_input_tokens: number }
/**
 * Snapshot payload of the singleton workspace entity. Typed here (the
 * runtime is its producer); opaque JSON from the hub outward.
 */
export type WorkspaceSnapshot = { 
/**
 * Canonical workspace directories; first is the primary dir.
 */
directories: string[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
