[package]
name = "frances"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[[bin]]
name = "frances"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
libc.workspace = true
parking_lot.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
frances-models-ui.workspace = true
frances-session.workspace = true
serde.workspace = true
serde_json.workspace = true
specta.workspace = true
specta-typescript.workspace = true
tauri.workspace = true
tauri-plugin-dialog.workspace = true
tauri-specta.workspace = true
xdg.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
gdk.workspace = true
gtk.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dev-dependencies]
