[package]
name = "frances-markdown"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
crossterm.workspace = true
frances-models-tui.workspace = true
frances-tui.workspace = true
ratatui.workspace = true
markdown.workspace = true
unicode-width.workspace = true

[dev-dependencies]
